### ISSUE TITLE
naming and saving patches

### ISSUE THREAD

**Issue by afcondon** [ElliotGarbus/Hedra-Editor-and-librarian#1]
i must be missing something obvious here but i see an unanswered question on the YouTube channel about it, so i figure at least one other person has the same question: how do you rename a patch? 

relatedly, if you drag a library patch into the preset list and edit it, if you try to save to Hedra & lib it will always say "The sound in in the Library as: <Preset Name>" but it doesn't offer a chance to edit the name at this point either.

Amazingly useful tool for sound design but it'd be super to be able to edit presets...i expect the workaround is to edit the JSON directly so i'll try that but i thought i'd log an issue anyway.

**Comment by ElliotGarbus** [comment]
The Meris pedals do not not store the names in the HW.  The app does a "reverse look up" to associate the name with the patch.  This requires that patch data must be unique, and the patch name must be unique.  If you are updating a patch name, give it a new name.  For example if you are editing a particular patch, give it a unique name on each save,,, MyPatch1, MyPatch2...

If you have saved saved a patch that has the same data as another patch file, the librarian will not save the data, and you will see the error message.

**Comment by afcondon** [comment]
But the app doesn't appear to allow you to rename a patch? that's why i say i must surely be missing something?

**Comment by afcondon** [comment]
Okay,  i found that if you delete patch X in the library first then you _are_ offered a dialog to name the patch. it still doesn't seem to save what i expect it to save (ie key info didn't appear to persist)

i think your workflow using the app must be much different from what i'd expect (maybe it's just me?). I'm going to rewatch your videos on it but i think maybe just a text write up of the intended use-cases would help.

**Comment by ElliotGarbus** [comment]
I have updated the editor.  It now allows the update of a preset without changing the name.
