### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by tandrewnichols** [ElliotGarbus/Hedra-Editor-and-librarian#3]
I was about to open issue that I don't understand the editors cause they don't see to do what I'd expect, but after watching the youtube video, I see that the pedal is just not connected because my editor still says "Connect" rather than "Connected." Which I don't understand because I can tweak parameters in the interface, and it is definitely (I am 100% sure about this) updating the pedal. I've double checked the midi settings and channel. But I can't save presets or change their names or anything, presumably because it's not connected. My connection looks like: MacOS -> USB -> Mastermind PBC 10 -> standard MIDI cable -> Disaster Area Design MIDI Box 4 -> standard MIDI cable -> Disaster Area MIDI Box -> 1/4 inch TRS cable -> pedal (sorry, it's part of a longer chain). I am assuming you might want me to try connecting directly, but 1) I don't know how to do that. 1/4 inch MIDI to USB-C isn't a thing I don't think. If I had a 1/4 inch to 5 pin MIDI cable, maybe I could go directly to my Scarlett, but I don't. 2) I was really hoping to be able to use the editor (and indeed _multiple_ editors) without having to swap cables all the time - just sit down and plug my Mastermind into my laptop and go.

**Comment by ElliotGarbus** [comment]
It looks the Mastermind PCB 10 should work as the MIDI interface, if MIDI forwarding is turned on.  The problem with your MIDI chain is the DisasterArea Midi boxes.  The editor requires a bi-directional connection to the pedal - both MIDI In and MIDI Out must be connected.  The Disaster Area boxes are for sending MIDI to the device, the do not have a path to get signal from the pedal back the the editor.  I'd recommend the Meris MIDI I/O.  Other alternatives include the Strymon Conduit or the Empress MIDIBox2 (The EMB2 has 1 bi-directional 1/4 port).

**Comment by tandrewnichols** [comment]
I didn't finish the path, but it is eventually connected back to the mastermind. That is, I have MIDI out from the mastermind through a chain to each pedal and back to the mastermind MIDI in. I think the disaster area midi boxes and meris midi io are identical?

**Comment by tandrewnichols** [comment]
Well, maybe you are right. The DAD boxes only say "MIDI output ports." That is immensely annoying. I wouldn't have bought them in that case.

**Comment by ElliotGarbus** [comment]
Yes, I'm 100% certain the DA Midibox is a one-way midi path.  I use the Meris MIDI box, it works very well and there is no configuration.   I have not used the Conduit - but it looks very good and provides a USB-C to 1/4 TRS bi-directional connection.  It also supports a wider set of devices.  The "problem" with these 1/4" midi products is that they are non-standard proprietary connections.  Good Luck!  Let me know when you're up and running.  Happy to help.

**Comment by tandrewnichols** [comment]
Those other products also cost way more. Do the two you named support all the varieties of midi that the DAD ones do? Cause I have Meris, Chase Bliss, Strymon, and Jackson Audio connected right now.

**Comment by ElliotGarbus** [comment]
The Strymon Conduit will support all of those connections and is configurable and full featured.  The Meris MIDI I/O should support the Strymon & Meris (I have not tested this) out of the box.  Supporting the ChaseBliss and Jackson - I suspect will require a custom cable from the 1/4 inch out of the Meris MIDI I/O.  You might want to look at adding the Meris MIDI I/O for the Meris pedals and keeping the MB4 for some of the other devices.

**Comment by tandrewnichols** [comment]
I think if it supports Strymon, it will support Jackson Audio cause they use the same dipswitch setting on the DAD device (TRS MIDI). The Meris site does say the Chase Bliss ones require a different cable.

So the Meris and Chase Bliss support bi-direction MIDI . . . is that it? I know the Jackson ones don't. Are there Strymon ones that do? (Just trying to think about how many bi-directional inputs I need)

**Comment by ElliotGarbus** [comment]
Meris and Strymon pedals are bi-directional.  This is required for an editor or librarian – but not if you are just controlling the device for performance (sending PC or CC messages).
The ChaseBliss and Jackson pedals only received MIDI.
The Jackson pedals connection is compliant with the (relatively new 1/4") MIDI standard.  The ChaseBilss pedals are not.

**Comment by tandrewnichols** [comment]
Okay, that is good news, cause I THINK that means I only need _one_ other midi box _AND_ that the Meris one is sufficient (cause I can use my existing DAD boxes for the Chase Bliss and Jackson).

Thanks for your help, I appreciate it.

**Comment by ElliotGarbus** [comment]
For your consideration - depending on how you want things connected together, you may need to get a midi thru box.  This would take one midi out as input and create multiple copies of the same midi out.  An example: http://midisolutions.com/prodqth.htm

**Comment by tandrewnichols** [comment]
Hmm . . . I don't _think_ I need that? What is the use case for that? Just for clarity, my full midi flow is Mastermind->DAD Midi Box 4->DAD MIdi Box->DAD DPC.micro->Strymon Timline->GFI Synesthesia->Source Audio Nemesis->Source Audio Ventris->Mastermind, so I don't _currently_ have any dead ends. And if the Meris box handles the bi-directionality of the pedals that need it . . . I think that is sufficient probably?

**Comment by ElliotGarbus** [comment]
If the Meris MIDI I/O is at the end of the chain - and all of the devices before it provide midi-thru,  I don't think you would need a MIDI-thru box.  If there is a break in the chain - you would need a Midi Thru box.

**Comment by tandrewnichols** [comment]
> If the Meris MIDI I/O is at the end of the chain
> If there is a break in the chain

I think I don't understand the juxtaposition here. It is not at the end of the chain, but there is no break in the chain and all the pedals provide midi thru. Will the meris midi i/o send messages it gets from the meris pedals on through the rest of the chain (and ultimately to my midi controller and on to my laptop)? Forgive me, I am only learning midi stuff right now.

**Comment by ElliotGarbus** [comment]
For the Meris pedals to forward midi messages the pedal must be set to midi thru.  To use the editor they must be set to midi out. If they are set to MIDI out, they will not forward the messages.

**Comment by ElliotGarbus** [comment]
It is also worth highlighting that not all midi pedals do exactly what the spec calls for... The editor sends and received SYSEX messages.  I don't know any of your pedals will have a problem passing SYSEX messages.  I do know that some pedals will not forward sysex.

**Comment by tandrewnichols** [comment]
I think I still don't understand, sorry. Maybe I don't understand how the meris midi i/o works. My assumption was that it would receive a message from 5-pin midi in, send it to the 4 qtr inch outs _and also forward it on through the 5-pin midi out_. In which case the individual meris pedals (e.g. hedra) would not _need_ to forward messages. Is that not how it works?

**Comment by tandrewnichols** [comment]
I have the hedra set to midi out right _now_, but I'm still receiving messages further down the chain, so unless the meris midi i/o works differently (bi-directional aside) from the DAD boxes, it seems like things should be okay....?

**Comment by ElliotGarbus** [comment]
Reading the manual for the Meris MIDI I/O, it looks like they are relying on a pedal set to thru to create the midi thru.  It is not 100% clear - but it looks like there is no alternative thru path.  I suggest you send them an email to find out.

**Comment by ElliotGarbus** [comment]
The DAD box is providing the MIDI Thru.

**Comment by tandrewnichols** [comment]
It looks like the pedals forward messages either way. From the manual (Section 1c):

> MIDI Thru:
Knob turns and switch presses do not create any MIDI messages. Any MIDI input messages that the pedal receives are passed along to the output (which creates the “thru”). This is the most typical mode. Use this mode if only want to use MIDI to control the pedal and you would not like to use the pedal to control any other gear further down the chain.
MIDI Out:
For every knob turn and button switch on your pedal, a MIDI messages is sent to the output. Any MIDI input messages that the pedal receives are also passed along to the output as well. Use this mode if you want to synchronize with or control external gear, like recording MIDI knob movements with your DAW.

In the MIDI Out section it still says "Any MIDI input messages that the pedal receives are also passed along to the output as well." So I think the only difference is whether turning knobs creates outgoing messages.

**Comment by ElliotGarbus** [comment]
Looks like that should be all good.  Sorry for the false alarm!

**Comment by tandrewnichols** [comment]
No worries, although yes, I did panic for a moment cause I had just ordered the midi io!
