### ISSUE TITLE
stuck on "reading presets

### ISSUE THREAD

**Issue by aheigl** [ElliotGarbus/Hedra-Editor-and-librarian#4]

**Comment by ElliotGarbus** [comment]
Stuck on reading presets indicates data is not being returned from the pedal to the editor.  This is most often caused by the selection of midi interface device, or a configuration error.

How are your connecting the Hedra to the computer?

**Comment by aheigl** [comment]
Hey, sorry, there was a whole explanation here that didn't get pasted.  the editor HAS worked for me in the past, but is no longer -- I'm using the Roland UM-One-MkII into the Meris I/O box into the Hedra. The Hedra is configured correctly for the editor.

I just updated both my Mac Os to Montery 12.6.1 AND the driver for my Roland UM-One-MkII, which solved the preset load issue, but now I'm getting "Fatal MIDI error" and "run audio midi setup." 

I ran the midi setup and it's showing the UM-One as sending data, per the Roland setup, not sure about returning it.

**Comment by aheigl** [comment]
Interestingly, it stops returning that fatal error when I change the midi channel in the editor and on the Hedra to 2 instead of one, but now it's back the original "reading presets" error

**Comment by ElliotGarbus** [comment]
Try leaving the audio midi set up open, do not close the window.  This may address the issue.
Make sure the connectors are well connected, both of the MIDI cables and the TRS cable.

When the device is correctly connected, turning the knobs on the device will cause the corresponding knob on the window to turn.

**Comment by aheigl** [comment]
back to the reading presets freeze. 

I can see via the UM-One's "out" light blinking that it's sending data, and the hedra's lights blink when I initially press "connect," but it just doesn't seem to be sending anything back.

**Comment by ElliotGarbus** [comment]
Make sure the Hedra is configured for MIDI OUT

**Comment by aheigl** [comment]
yup, even tried switching it back and forth. still hung on the reading presets screen

**Comment by ElliotGarbus** [comment]
check that the midi in and out ports are not swapped.  Are you seeing the leds light up on the midi interface the way you would expect?

**Comment by ElliotGarbus** [comment]
Also ensure you are using a TRS cable from the pedal to the Midi IO.

**Comment by aheigl** [comment]
yup, the TRS thing was it. I'm an idiot. Thanks, Elliott!

**Comment by ElliotGarbus** [comment]
Glad to here you’re up and running.
